## PRODUCTS
##Get all products
#GET http://localhost:8080/api/products

## GET request to retrieve a product by name
#GET http://localhost:8080/api/products/Face wash
#Content-Type: application/json

## GET request to retrieve a product by name (non-existent product)
#GET http://localhost:8080/api/products/Facewash
#Content-Type: application/json

## GET request to retrieve products by price
#GET http://localhost:8080/api/products/price/200

## GET request to retrieve products by price (no products with this price)
#GET http://localhost:8080/api/products/price/121

## GET request to retrieve products from category
#GET http://localhost:8080/api/products/category/Face Products

## GET request to retrieve products from category(non-existent category)
#GET http://localhost:8080/api/products/category/121

## GET request to retrieve products from brand
#GET http://localhost:8080/api/products/brand/Brand1

## GET request to retrieve products from brand(non-existent brand)
#GET http://localhost:8080/api/products/brand/121

## GET request to retrieve products by skin type
#GET http://localhost:8080/api/products/skinType/OILY

## GET request to retrieve products by skin type (non-existent skin type)
#GET http://localhost:8080/api/products/skinType/121


## POST request to create a new product with non-existent category
#POST http://localhost:8080/api/products
#Content-Type: application/json
#
#{
#  "name": "New Product",
#  "price": 20,
#  "categoryName": "Non-Existent Category",
#  "brandName": "Brand1",
#  "skinTypeName": "OILY"
#}

##POST request to create a new product with non-existent brand
#POST http://localhost:8080/api/products
#Content-Type: application/json
#
#{
#  "name": "New Product",
#  "price": 20,
#  "categoryName": "Face Products",
#  "brandName": "Non-existent brand",
#  "skinTypeName": "OILY"
#}

## POST request to create a new product with non-existent skin type
#POST http://localhost:8080/api/products
#Content-Type: application/json
#
#{
#  "name": "New Product",
#  "price": 20,
#  "categoryName": "Face Products",
#  "brandName": "Brand1",
#  "skinTypeName": "Non-existent skin type"
#}


## POST request to create a new product
#POST http://localhost:8080/api/products
#Content-Type: application/json
#
#{
#"name": "New Product1",
#"price": 20,
#"categoryName": "New Category",
#"brandName": "Brand1",
#"skinTypeName": "OILY"
#}


## POST request to create indentical new product
#POST http://localhost:8080/api/products
#Content-Type: application/json
#
#{
#"name": "New Product1",
#"price": 20,
#"categoryName": "Face Products",
#"brandName": "Brand1",
#"skinTypeName": "OILY"
#}

## GET request to get a product by name
#GET http://localhost:8080/api/products/New Product1
#ontent-Type: application/json

## PUT request to update an existing product
#PUT http://localhost:8080/api/products/bfbb79b3-e6c0-49ad-98e7-8090e468b19b
#Content-Type: application/json
#
#{
#  "name": "new name",
#  "price": 25,
#  "categoryName": "Face Products",
#  "brandName": "Brand1",
#  "skinTypeName": "OILY"
#}

## GET request to get a product by NEW name
#GET http://localhost:8080/api/products/new name
#ontent-Type: application/json

## PUT request to update an existing product(Non-existent category)
#PUT http://localhost:8080/api/products/99ceca95-8424-413c-b83a-85f475aae521
#Content-Type: application/json
#
#{
#  "name": "new name",
#  "price": 25,
#  "categoryName": "Face Products1",
#  "brandName": "Brand1",
#  "skinTypeName": "OILY"
#}

## PUT request to update an existing product(Non-existent brand)
#PUT http://localhost:8080/api/products/99ceca95-8424-413c-b83a-85f475aae521
#Content-Type: application/json
#
#{
#  "name": "new name",
#  "price": 25,
#  "categoryName": "Face Products",
#  "brandName": "Brand11",
#  "skinTypeName": "OILY"
#}

## PUT request to update an existing product(Non-existent skin type)
#PUT http://localhost:8080/api/products/99ceca95-8424-413c-b83a-85f475aae521
#Content-Type: application/json
#
#{
#  "name": "new name",
#  "price": 25,
#  "categoryName": "Face Products",
#  "brandName": "Brand1",
#  "skinTypeName": "OILY1"
#}

## DELETE request to delete a product
#DELETE http://localhost:8080/api/products/99ceca95-8424-413c-b83a-85f475aae521

## DELETE request to delete a product (non-existent product)
#DELETE http://localhost:8080/api/products/99ceca95-8424-413c-b83a-85f475aae521


## CATEGORIES

## GET request to retrieve all categories
#GET http://localhost:8080/api/categories

## GET request to retrieve a category by name
#GET http://localhost:8080/api/categories/Face Products

## GET request to retrieve a category by name (non-existent category)
#GET http://localhost:8080/api/categories/Face Products1

## GET request to get all products from a category
#GET http://localhost:8080/api/categories/New Category/products

## GET request to get all products from a category (non-existent category)
#GET http://localhost:8080/api/categories/Face Products1/products

## POST request to create a new category
#POST http://localhost:8080/api/categories
#Content-Type: application/json
#
#{
#  "name": "New Category",
#  "code": 4
#}

## POST request to create a new category (identical category)
#POST http://localhost:8080/api/categories
#Content-Type: application/json
#
#{
#  "name": "New Category",
#  "code": 4
#}

## POST request to create a new category (no name and code field)
#POST http://localhost:8080/api/categories
#Content-Type: application/json
#
#{
#  "name2": "New Category",
#  "code2": 4
#}

## PUT request to update an existing category
#PUT http://localhost:8080/api/categories/8af8d03f-d059-4284-914c-1cbfc3756689
#Content-Type: application/json
#
#{
#  "name": "New Category1",
#  "code": 4
#}

## PUT request to update an existing category (non-existent category)
#PUT http://localhost:8080/api/categories/99ceca95-8424-413c-b83a-85f475aae521
#Content-Type: application/json
#
#{
#  "name": "New Category1",
#  "code": 4
#}

## DELETE request to delete a category
#DELETE http://localhost:8080/api/categories/724afc19-429e-4db9-8e5c-e00c70b131a4

## DELETE request to delete a category (non-existent category)
#DELETE http://localhost:8080/api/categories/99ceca95-8424-413c-b83a-85f475aae521


## BRANDS

## GET request to retrieve all brands
#GET http://localhost:8080/api/brands

## GET request to retrieve a brand by name
#GET http://localhost:8080/api/brands/Brand1

## GET request to retrieve a brand by name (non-existent brand)
#GET http://localhost:8080/api/brands/Brand11

## GET request to get all products from a brand
#GET http://localhost:8080/api/brands/Brand1/products

## GET request to get all products from a brand (non-existent brand)
#GET http://localhost:8080/api/brands/Brand11/products

## POST request to create a new brand
#POST http://localhost:8080/api/brands
#Content-Type: application/json
#
#{
#  "name": "New Brand"
#}

## POST request to create a new brand (identical brand)
#POST http://localhost:8080/api/brands
#Content-Type: application/json
#
#{
#  "name": "New Brand"
#}

## POST request to create a new brand (no name)
#POST http://localhost:8080/api/brands
#Content-Type: application/json
#
#{
#  "name2": "New Brand"
#}

## PUT request to update an existing brand
#PUT http://localhost:8080/api/brands/22378158-d0ca-4b47-9153-1976d18422e7
#Content-Type: application/json
#
#{
#  "name": "New Brand2 NAME"
#}

## PUT request to update an existing brand (non-existent brand)
#PUT http://localhost:8080/api/brands/99ceca95-8424-413c-b83a-85f475aae521
#Content-Type: application/json
#
#{
#  "name": "New Brand1"
#}

## DELETE request to delete a brand
#DELETE http://localhost:8080/api/brands/22378158-d0ca-4b47-9153-1976d18422e7

## DELETE request to delete a brand (non-existent brand)
#DELETE http://localhost:8080/api/brands/99ceca95-8424-413c-b83a-85f475aae521


##SKIN TYPES

## GET request to retrieve all skin types
#GET http://localhost:8080/api/skinTypes

## GET request to retrieve a skin type by name
#GET http://localhost:8080/api/skinTypes/DEHYDRATED

## GET request to retrieve a skin type by name (non-existent skin type)
#GET http://localhost:8080/api/skinTypes/OILY1

## GET request to get all products from a skin type
#GET http://localhost:8080/api/skinTypes/DEHYDRATED/products

## GET request to get all products from a skin type (non-existent skin type)
#GET http://localhost:8080/api/skinTypes/OILYQ/products

## POST request to create a new skin type
#POST http://localhost:8080/api/skinTypes
#Content-Type: application/json
#
#{
#  "name": "New Skin Type"
#}

## POST request to create a new skin type (identical skin type)
#POST http://localhost:8080/api/skinTypes
#Content-Type: application/json
#
#{
#  "name": "New Skin Type"
#}

## POST request to create a new skin type (no name)
#POST http://localhost:8080/api/skinTypes
#Content-Type: application/json
#
#{
#  "name2": "New Skin Type"
#}

## PUT request to update an existing skin type
#PUT http://localhost:8080/api/skinTypes/ad631e86-1885-4494-a475-15b2b3ccbb84
#Content-Type: application/json
#
#{
#  "name": "New Skin Type2 NAME"
#}

## PUT request to update an existing skin type (non-existent skin type)
#PUT http://localhost:8080/api/skinTypes/99ceca95-8424-413c-b83a-85f475aae521
#Content-Type: application/json
#
#{
#  "name": "New Skin Type1"
#}

## DELETE request to delete a skin type
#DELETE http://localhost:8080/api/skinTypes/58c7837a-e7c6-4e1a-9b1c-1c3b9b9a48d9

## DELETE request to delete a skin type (non-existent skin type)
#DELETE http://localhost:8080/api/skinTypes/99ceca95-8424-413c-b83a-85f475aae521




