#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: products-route
#          uri: http://localhost:8086  # Replace with the actual URL of your Product microservice
#          predicates:
#            - Path=/api/product/**
#
#        - id: categories-route
#          uri: http://localhost:8085  # Replace with the actual URL of your Category microservice
#          predicates:
#            - Path=/api/categories/**
#
